// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6JSClNTKx2bw5QiDbdZn1m2w0QflfJMI',
    appId: '1:132617993405:web:9da324f3fa09c2eb704bd4',
    messagingSenderId: '132617993405',
    projectId: 'studybuddy-6d90b',
    authDomain: 'studybuddy-6d90b.firebaseapp.com',
    storageBucket: 'studybuddy-6d90b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDpWzUmO3wargMfR7k1bia89_95ISY09w',
    appId: '1:132617993405:android:a29817a88e815e4f704bd4',
    messagingSenderId: '132617993405',
    projectId: 'studybuddy-6d90b',
    storageBucket: 'studybuddy-6d90b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6JSClNTKx2bw5QiDbdZn1m2w0QflfJMI',
    appId: '1:132617993405:web:899cc10116d8a4ae704bd4',
    messagingSenderId: '132617993405',
    projectId: 'studybuddy-6d90b',
    authDomain: 'studybuddy-6d90b.firebaseapp.com',
    storageBucket: 'studybuddy-6d90b.firebasestorage.app',
  );
}
