# Generated by Django 5.2.1 on 2025-05-14 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('at_risk', 'At-Risk Student Identification'), ('subject_performance', 'Subject Performance Prediction'), ('tutor_matching', 'Optimal Tutor Matching'), ('session_recommendation', 'Session Recommendation'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('parameters', models.JSONField(default=dict)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('f1_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('precision', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('recall', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('trained_on', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Predictive Model',
                'verbose_name_plural': 'Predictive Models',
            },
        ),
        migrations.CreateModel(
            name='RecommendedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('tutoring_session', 'Attend Tutoring Session'), ('tutor_assignment', 'Assign as Tutor'), ('material_review', 'Review Learning Material'), ('instructor_meeting', 'Meet with Instructor'), ('peer_collaboration', 'Collaborate with Peers'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recommended Action',
                'verbose_name_plural': 'Recommended Actions',
            },
        ),
        migrations.CreateModel(
            name='StudentProgressMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('sessions_attended', models.IntegerField(default=0)),
                ('total_learning_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('questions_asked', models.IntegerField(default=0)),
                ('feedback_given_count', models.IntegerField(default=0)),
                ('self_reported_confidence', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('self_reported_understanding', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Progress Metric',
                'verbose_name_plural': 'Student Progress Metrics',
            },
        ),
        migrations.CreateModel(
            name='StudentRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=10)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contributing_factors', models.JSONField(default=dict)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Student Risk Assessment',
                'verbose_name_plural': 'Student Risk Assessments',
            },
        ),
        migrations.CreateModel(
            name='SubjectAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_tutoring_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_session_duration', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active_tutors', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('student_to_tutor_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_session_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('feedback_response_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject Analytic',
                'verbose_name_plural': 'Subject Analytics',
            },
        ),
        migrations.CreateModel(
            name='TutorPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('sessions_conducted', models.IntegerField(default=0)),
                ('total_tutoring_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('feedback_count', models.IntegerField(default=0)),
                ('unique_students_helped', models.IntegerField(default=0)),
                ('repeat_students', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutor Performance Metric',
                'verbose_name_plural': 'Tutor Performance Metrics',
            },
        ),
        migrations.CreateModel(
            name='InstitutionAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('active_subjects', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_tutoring_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_instructors', models.IntegerField(default=0)),
                ('active_tutors', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('student_participation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_session_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('average_tutor_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('average_content_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('points_awarded', models.IntegerField(default=0)),
                ('achievements_unlocked', models.IntegerField(default=0)),
                ('rewards_redeemed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution Analytic',
                'verbose_name_plural': 'Institution Analytics',
                'unique_together': {('period_start', 'period_end')},
            },
        ),
    ]
