# Generated by Django 5.2.1 on 2025-05-14 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedaction',
            name='related_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutoring.learningmaterial'),
        ),
        migrations.AddField(
            model_name='recommendedaction',
            name='related_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutoring.tutoringsession'),
        ),
    ]
