# Generated by Django 5.2.1 on 2025-05-14 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('tutoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedaction',
            name='related_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendedaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendedaction',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_actions', to='tutoring.subject'),
        ),
        migrations.AddField(
            model_name='studentprogressmetric',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprogressmetric',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_metrics', to='tutoring.subject'),
        ),
        migrations.AddField(
            model_name='studentriskassessment',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='analytics.predictivemodel'),
        ),
        migrations.AddField(
            model_name='studentriskassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentriskassessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='tutoring.subject'),
        ),
        migrations.AddField(
            model_name='recommendedaction',
            name='based_on_risk_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.studentriskassessment'),
        ),
        migrations.AddField(
            model_name='subjectanalytic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='tutoring.subject'),
        ),
        migrations.AddField(
            model_name='tutorperformancemetric',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_metrics', to='tutoring.subject'),
        ),
        migrations.AddField(
            model_name='tutorperformancemetric',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentprogressmetric',
            unique_together={('student', 'subject', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectanalytic',
            unique_together={('subject', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='tutorperformancemetric',
            unique_together={('tutor', 'subject', 'period_start', 'period_end')},
        ),
    ]
