# Generated by Django 5.2.3 on 2025-06-24 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='emoji_events', max_length=50)),
                ('earned', models.BooleanField(default=False)),
                ('progress', models.FloatField(default=0.0)),
                ('earned_date', models.DateTimeField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_completed', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('badges_earned', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('upcoming_sessions', models.IntegerField(default=0)),
                ('pending_sessions', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
