# Generated by Django 5.2.3 on 2025-06-24 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('tutor_name', models.CharField(max_length=100)),
                ('tutor_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('platform', models.CharField(default='Google Meet', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('pending', 'Pending'), ('declined', 'Declined'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('participant_images', models.JSONField(default=list)),
                ('is_current_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
